# .scrutinizer.yml

checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php: '7.1'

  dependencies:
    before:
      - pecl install igbinary
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=.soupmix_coverage'
        coverage:
          file: '.soupmix_coverage'
          format: 'clover'
filter:
  excluded_paths:
    - "tests/"